version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    command: --nojournal
    networks:
      - fiware
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  orion:
    container_name: orion
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -dbuser root -dbpwd example
    depends_on:
      - mongo
    networks:
      - fiware
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
      - "ORION_HOST=http://orion:1026"
      - "NOTIFICATION_HOST=http://spark-master"
    networks:
         - fiware
    volumes:
      - ./prediction-job:/prediction-job
      - /spark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "9002:9001"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
      - "ORION_HOST=http://orion:1026"
      - "NOTIFICATION_HOST=http://spark-worker-1"
    volumes:
      - ./prediction-job:/prediction-job
    networks:
        - fiware

  zeppelin-spark: 
    image: apache/zeppelin:0.9.0
    container_name: zeppelin-spark
    ports: 
      - "8079:8080"
      - "9003:9001"
    volumes: 
      - ./dependencies:/zeppelin/external-jars
      - ./prediction-job:/prediction-job
    volumes_from: 
      - spark-master:ro
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/spark"
      - "SPARK_SUBMIT_OPTIONS= --jars /zeppelin/external-jars/orion.spark.connector-1.3.0.jar"
    depends_on:
      - spark-master
    networks:
      - fiware

  draco:
    image: ging/fiware-draco
    container_name: draco
    depends_on:
      - orion
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    ports:
      - "9090:9090"
      - "5050:5050"
    networks:
      - fiware

  python:
    image: python:3
    container_name: python
    depends_on:
      - draco
    environment:
      - DRACO_ENDPOINT=draco:9090
    networks:
      - fiware
    command: bash -c "sleep 120 && pip install --no-cache-dir -r /entities/requirements.txt && python /entities/runDraco.py && sh /entities/subscribeResPredictionTicketDraco.sh"
    volumes:
      - ./entities:/entities

  
networks:
  fiware:
