version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:3.4
    command: --nojournal
    networks:
      - fiware
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  orion:
    container_name: orion
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -dbuser root -dbpwd example #-logLevel DEBUG
    networks:
      - fiware
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - orion
    networks:
      - fiware
    command: bash -c "sh /entities/createPredictionEntities.sh && sh /entities/subscribeReqPredictionTicket.sh && sh /entities/subscribeResPredictionTicket.sh && npm start"
    environment:
      - URL_CB=http://orion:1026/v2/entities/ReqTicketPrediction1/attrs
      - MONGO_URI=mongodb://root:example@mongo:27017/sth_test?authSource=admin
    volumes:
      - ./entities:/entities
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
#    depends_on:
#      - maven
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - fiware
#    command: bash -c "sleep 12 && sh /prediction-job/run-spark-jobs.sh"
    volumes:
      - ./prediction-job:/prediction-job
      - /spark

  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    volumes:
      - ./prediction-job:/prediction-job
    networks:
        - fiware
  # maven:
  #   image: ging/maven
  #   container_name: maven
  #   expose:
  #     - "8092"
  #   ports:
  #       - "8092:8092"
  #   environment:
  #     - "SPARK_MASTER=spark-master:7077"
  #   volumes:
  #     - ./prediction-job:/prediction-job
  #   networks:
  #     - fiware
  # draco:
  #   image: ging/fiware-draco
  #   container_name: draco
  #   depends_on:
  #     - orion
  #   environment:
  #     - NIFI_WEB_HTTP_PORT=9090
  #   ports:
  #     - "9090:9090"
  #     - "5050:5050"
  #   networks:
  #     - fiware

  # python:
  #   image: python:3
  #   container_name: python
  #   #depends_on:
  #   #  - draco
  #   environment:
  #     - DRACO_ENDPOINT=draco:9090
  #   networks:
  #     - fiware
  #   #command: bash -c "pip install --no-cache-dir -r /entities/requirements.txt && python /entities/runDraco.py && sh /entities/subscribeResPredictionTicketDraco.sh"
  #   command: bash -c "sh /entities/subscribeResPredictionTicket.sh"
  #   volumes:
  #     - ./entities:/entities
  zeppelin-spark: 
    image: apache/zeppelin:0.9.0
    container_name: zeppelin-spark
    ports: 
      - "8079:8080"
    volumes: 
      - ./dependencies:/zeppelin/external-jars
      - ./prediction-job:/prediction-job
    volumes_from: 
      - spark-master:ro
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/spark"
      - "SPARK_SUBMIT_OPTIONS= --jars /zeppelin/external-jars/orion.spark.connector-1.2.3.jar"
    depends_on:
      - spark-master
    networks:
      - fiware

  
networks:
  fiware:
