version: "2"
services:
 # mongo:
 #   container_name: mongo
 #   image: mongo:3.4
 #   command: --nojournal
 #   networks:
 #     - fiware
 # orion:
 #   container_name: orion
 #   image: fiware/orion
 #   links:
 #     - mongo
 #   ports:
 #     - "1026:1026"
 #   command: -dbhost mongo
 #   networks:
 #     - fiware
 #     - dockernet
 # web:
 #   container_name: web
 #   build:
 #     context: ./web
 #   ports:
 #     - "8080:8080"
 #   networks:
 #     - fiware
 #   environment:
 #     - URL_CB=http://orion:1026/v2/entities/ReqTicketPrediction1/attrs
 #   deploy:
 #     restart_policy:
 #       condition: on-failure
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - fiware
    volumes:
      - ./prediction-job/target:/prediction-job

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    networks:
        - fiware
  maven:
    image: ging/maven
    container_name: maven
    depends_on:
      - spark-master
    expose:
      - "8092"
    ports:
        - "8092:8092"
    environment:
      - "SPARK_MASTER=spark-master:7077"
    volumes:
      - ./prediction-job:/prediction-job
    networks:
      - fiware

networks:
  fiware:
  dockernet:
    external: true