version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    command: --nojournal
    networks:
      - fiware
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  orion:
    container_name: orion
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -dbuser root -dbpwd example
    depends_on:
      - mongo
    networks:
      - fiware
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - fiware
    volumes:
      - ./prediction-job:/prediction-job
      - /spark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "9002:9001"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    volumes:
      - ./prediction-job:/prediction-job
    networks:
        - fiware
  zeppelin-spark: 
    image: apache/zeppelin:0.9.0
    container_name: zeppelin-spark
    ports: 
      - "8079:8080"
      - "9003:9001"
    volumes: 
      - ./dependencies:/zeppelin/external-jars
      - ./prediction-job:/prediction-job
    volumes_from: 
      - spark-master:ro
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/spark"
      - "SPARK_SUBMIT_OPTIONS= --jars /zeppelin/external-jars/orion.spark.connector-1.2.1.jar"
    depends_on:
      - spark-master
    networks:
      - fiware

  
networks:
  fiware:
